apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-db-credentials
  namespace: ecommerce
type: Opaque
data:
  # base64 encoded: ecommerce123
  DB_PASSWORD: ZWNvbWFuYWx5c2EyMw==
  # base64 encoded: rootpassword
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  # base64 encoded: SecureKey123!
  API_SECRET_KEY: U2VjdXJlS2V5MTIzIQ==
